// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUjg2iPw6qBsOTOaTAyLNBTWNj630YuI',
    appId: '1:495617804531:web:e0ffe16558a0e3baa14f86',
    messagingSenderId: '495617804531',
    projectId: 'chatbot-4c6b9',
    authDomain: 'chatbot-4c6b9.firebaseapp.com',
    storageBucket: 'chatbot-4c6b9.appspot.com',
    measurementId: 'G-M1L1N65R6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-cxtC09JG6fHKgV8yWy2In8t_JXoo30',
    appId: '1:495617804531:android:6b3d8aa3cc392869a14f86',
    messagingSenderId: '495617804531',
    projectId: 'chatbot-4c6b9',
    storageBucket: 'chatbot-4c6b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9O5oXZ1TPDnyvtaTOLx5T7qbV-VNf1-k',
    appId: '1:495617804531:ios:285ba52ffbab3a34a14f86',
    messagingSenderId: '495617804531',
    projectId: 'chatbot-4c6b9',
    storageBucket: 'chatbot-4c6b9.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9O5oXZ1TPDnyvtaTOLx5T7qbV-VNf1-k',
    appId: '1:495617804531:ios:285ba52ffbab3a34a14f86',
    messagingSenderId: '495617804531',
    projectId: 'chatbot-4c6b9',
    storageBucket: 'chatbot-4c6b9.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkUjg2iPw6qBsOTOaTAyLNBTWNj630YuI',
    appId: '1:495617804531:web:66e0979bb2ca9ca1a14f86',
    messagingSenderId: '495617804531',
    projectId: 'chatbot-4c6b9',
    authDomain: 'chatbot-4c6b9.firebaseapp.com',
    storageBucket: 'chatbot-4c6b9.appspot.com',
    measurementId: 'G-PM7342B64F',
  );
}
